name: Hello World

# Events

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

  
  # workflow / jobs
  
  jobs:
    hello:
      runs-on: ubuntu-latest
      step:
        - uses: actions/checkout@v4
        - name: Hello
        run: echo "Hello World"
        shell: bash
